# Generated by Django 5.1.8 on 2025-06-19 09:33

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "1068_alter_document_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paperlesstask",
            name="task_id",
            field=models.CharField(
                db_index=True,
                help_text="Celery ID for the Task that was run",
                max_length=255,
                unique=True,
                verbose_name="Task ID",
            ),
        ),
    ]
